name: Предложение
description: Новая возможность или улучшение
title: "feat: "
labels: ["enhancement", "triage"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Проблема пользователя
    validations:
      required: true
  - type: textarea
    id: outcome
    attributes:
      label: Желаемый результат
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Альтернативы и ограничения
